# NCE1 标准语法表（144课时体系，每2课=1单元）
# 依据《新概念英语》第一册标准语法大纲编写
NCE1_GRAMMAR = {
1: ["一般疑问句 Is this…?：用 Yes/No 回答", "人称代词主格与宾格（I/me, you/you, he/him…）", "物主代词 my 表示“我的”"],
2: ["一般疑问句 Are you…? 的肯定与否定回答", "名词所有格：-'s 表示所属（如 the boy's）", "形容词性物主代词 my/your"],
3: ["be 动词 am/is/are 的用法", "询问国籍：What nationality are you?", "介绍他人：This is… / Nice to meet you"],
4: ["一般疑问句与否定句（Is he…? He isn't…）", "询问职业：What's his job?", "人称代词与 be 动词搭配"],
5: ["How are you? 问候语及回答", "形容词作表语（fine, well, tired…）", "形容词性物主代词（her, his）"],
6: ["名词所有格：-'s（the boy's shirt）", "whose 引导的特殊疑问句", "一般疑问句 Is this your…?"],
7: ["What colour…? 询问颜色", "颜色形容词（red, blue, green…）", "名词修饰名词（a new dress）"],
8: ["询问国籍：Where do you come from?", "一般现在时 be 动词（am/is/are）", "国家与国籍名词（China, Chinese…）"],
9: ["How do you do? 初次见面问候", "一般疑问句 Are you…? / Is he…?", "特殊疑问句 What's your name?"],
10: ["形容词作表语（tired, thirsty, dirty…）", "Look at… 祈使句", "一般疑问句 Are you…? 的回答"],
11: ["Which 引导的特殊疑问句", "物主代词 mine/yours/hers", "名词性物主代词与形容词性物主代词"],
12: ["Which + 名词 的疑问句", "指示代词 this/that/these/those", "一般疑问句及否定回答"],
13: ["There be 句型（单数）", "名词所有格：Mrs. Smith's kitchen", "介词 in/on 表示位置"],
14: ["There be 句型（复数）", "方位介词 near/on/in", "名词复数变化（bookcases, shelves…）"],
15: ["祈使句：Come in, Amy", "情态动词 must（必须）", "动词原形用法"],
16: ["现在进行时：be + doing", "Where 引导的特殊疑问句", "动词 -ing 形式变化"],
17: ["现在进行时：What are you doing?", "一般现在时与现在进行时对比", "动词 -ing 形式（swimming, reading…）"],
18: ["一般现在时：描述日常状态", "介词 near/by/in 方位", "There be 句型复习"],
19: ["现在进行时（making…）", "一般将来时 be going to", "What…? 特殊疑问句"],
20: ["祈使句否定：Don't drop it!", "情态动词 can（能够）", "动词位置与宾语（drop it, put it）"],
21: ["不可数名词（bread, cheese, soap…）", "some 的用法", "一般疑问句 Is there any…?"],
22: ["一般将来时 will / be going to", "情态动词 must/can", "时间表达：in a minute"],
23: ["情态动词 can（can't）", "一般将来时（will）", "动词 + 宾语结构（type the letter）"],
24: ["可数名词与不可数名词", "some / any 的用法", "一般疑问句 Are there any…?"],
25: ["一般现在时：What do you want?", "名词复数（apples, oranges…）", "物主代词 mine/yours"],
26: ["一般现在时描述天气气候", "询问天气：What's the weather like?", "国家与天气（England, Germany…）"],
27: ["一般现在时描述气候", "一般疑问句 Does it…?", "频率词 always/usually/often"],
28: ["一般现在时第三人称单数", "频率副词（always, usually, often, sometimes）", "日常生活描述（Mrs. Sawyer's day）"],
29: ["一般现在时 vs 一般过去时", "时间状语（yesterday, last night）", "不规则动词过去式（went, saw…）"],
30: ["一般疑问句 Is that all?", "数量表达（a loaf, a bar…）", "不可数名词量词（a piece of…）"],
31: ["情态动词 must（必须做）", "一般现在时 have/has", "身体不适表达（have a cold, headache）"],
32: ["一般现在时描述状态", "情态动词 must 的肯定/否定", "身体部位与健康（temperature, better）"],
33: ["一般现在时（feels, is）", "物主代词/形容词描述", "年龄表达（She is three.）"],
34: ["一般过去时 was/were", "时间表达（at the weekend, on Sunday）", "过去时间状语"],
35: ["形容词比较级（-er/more）", "最高级（the -est）", "一般过去时 was/were 复习"],
36: ["一般过去时（was/were）", "时间状语（yesterday）", "反意疑问句（isn't he?）"],
37: ["一般过去时描述事件", "问路：How can I get to…?", "转折连词 but"],
38: ["一般过去时（不规则动词）", "形容词比较级（more comfortable）", "形容词作表语"],
39: ["一般过去时（had, went）", "时间表达（last night, this morning）", "情态动词 must"],
40: ["一般过去时（bought, made）", "不可数名词与量词", "购物场景表达"],
41: ["一般过去时（had, ate）", "不可数名词（meat, potatoes）", "部分表达：a piece of"],
42: ["现在完成时 have/has + 过去分词", "一般过去时对比", "时间副词（already, just）"],
43: ["现在完成时（have been）", "一般过去时对比", "城市描述（Paris in the spring）"],
44: ["一般过去时（was repairing）", "现在完成时（has been）", "事故描述（car crash）"],
45: ["一般过去时（had, bought）", "一般现在时描述现状", "价格表达（for sale）"],
46: ["现在完成时（have known）", "since/for 时间表达", "一般过去时对比"],
47: ["现在完成时（has moved）", "一般过去时对比", "居住表达（live in…）"],
48: ["一般过去时（went, took）", "名词复数与地点", "请求表达（tickets, please）"],
49: ["形容词顺序（a small blue case）", "物主代词（mine, yours）", "一般过去时（found, bought）"],
50: ["一般过去时（fell, hurt）", "反身代词（myself, himself）", "身体表达"],
51: ["现在完成时（has had）", "一般过去时对比", "信件/卡片表达"],
52: ["一般过去时（took, passed）", "考试与分数表达", "间接引语简介"],
53: ["一般过去时（made, corrected）", "名词所有格（teacher's book）", "工作场景（mistakes）"],
54: ["形容词比较级（smaller, larger）", "一般过去时（bought, tried）", "购物比较表达"],
55: ["一般将来时 will", "一般过去时（had）", "计划表达（is going to）"],
56: ["形容词最高级（the most expensive）", "比较级（cheaper, more expensive）", "一般现在时（is, costs）"],
57: ["一般过去时（went, bought）", "钱数表达（small change）", "反身代词（himself）"],
58: ["一般过去时（knocked, opened）", "情态动词 can", "拜访表达"],
59: ["一般过去时（had, was）", "房间与早餐词汇", "时间表达（at 6 o'clock）"],
60: ["一般过去时（heard, was）", "时间状语（at that moment）", "叙事结构"],
61: ["现在完成时（has been）", "一般过去时对比", "人物描述（in a hat）"],
62: ["现在完成时（has been）", "一般过去时对比", "旅行表达（trip to Australia）"],
63: ["现在完成时（has made）", "一般过去时对比", "邀请表达（tea for two）"],
64: ["一般过去时（was, became）", "现在完成时（has been）", "职业描述（famous actress）"],
65: ["现在完成时（has driven）", "情态动词 must/can", "速度表达（seventy miles an hour）"],
66: ["情态动词 mustn't / needn't", "一般将来时（will）", "猜测表达（Don't be so sure）"],
67: ["现在完成时（has had）", "新闻表达（sensational news）", "一般过去时对比"],
68: ["现在完成时（has been）", "一般过去时对比", "报告/新闻表达"],
69: ["一般过去时（dreamed, saw）", "情态动词（would）", "梦境描述"],
70: ["一般现在时（is, sounds）", "电话用语（Is that you?）", "辨认表达"],
71: ["一般过去时（made, saw）", "第一次体验（first train ride）", "叙事描述"],
72: ["一般过去时复习", "现在完成时复习", "综合语法运用（woods, walk）"],
}
